name: Deploy to Development

on:
  pull_request:
    branches: [ devel ]
    types: [ closed ]

jobs:
  deploy-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

  steps:
    - name: Deploy to Development Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        scripts: |
          cd /var/www/apps/employee-app-dev
          git fetch origin
          git reset --hard origin/devel
          npm ci
          npm run build
          pm2 restart employee-app-dev || pm2 start npm --name "employee-app-dev" -- start -- --port 3001