name: Deploy to Development

on:
  pull_request:
    branches: [ devel ]
    types: [ closed ]

jobs:
  deploy-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/apps/employee-app-dev
            echo "Current directory: $(pwd)"
            echo "Checking git remote:"
            git remote -v
            echo "Fetching changes..."
            git fetch origin || { echo "Git fetch failed"; exit 1; }
            echo "Resetting to origin/devel..."
            git reset --hard origin/devel || { echo "Git reset failed"; exit 1; }
            echo "Installing dependencies..."
            npm ci --legacy-peer-deps || { echo "npm ci failed"; exit 1; }
            echo "Building app..."
            npm run build || { echo "Build failed"; exit 1; }
            echo "Restarting app wtih PM2..."
            pm2 restart employee-app-dev || pm2 start npm --name "employee-app-dev" -- start -- --port 3001